---
name: 'Check Commit Messages'
description: 'Checks commit messages against a specified pattern'
inputs:
  commit-pattern:
    description: 'The commit message pattern to check against'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run composite action
      uses: ./composite-action.yml
      with:
        commit-pattern: ${{ inputs.commit-pattern }}