name: 'Add Topics to Repository'
description: 'Adds topics to the repository based on .project-properties.json'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  properties-file:
    description: 'The name of the properties file'
    required: false
    default: '.project-properties.json'
  org:
    description: 'The organization name'
    required: true
  repo:
    description: 'The repository name'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'