---
name: build-bundle
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies and build
        run: npm run install-and-build-all
      - name: Set environment variable for head ref
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: echo "HEAD_REF=${{ env.HEAD_REF }}" >> "$GITHUB_ENV"
      - name: Commit dist folders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ env.HEAD_REF }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add */dist
          # if git diff-index --quiet HEAD --; then
          #   echo "No changes to commit"
          #   exit 0
          # else
          git commit -m 'chores/update-dist: Build dist folders' || true
          git push origin "${{ env.HEAD_REF }}" || true
          # fi
